server:
  port: 8082

spring:
  application:
    name: Ms-Mail
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: email
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: "*"
      group-id: mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: YOUR_GMAIL_ADDRESS
    password: YOUR_PASSWORD_APPLICATION
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka