server:
  port: 8081

spring:
  application:
    name: Ms-User
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: email

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka